TABLE_RECORD_HEADERS = {
    "chats_raised": "Total Chat Raised",
    "chats_resolved": "Total Chat Resolved",
    "abandoned_chats": "Offline Chats",
    "offline_chats": "Missed Chats",
    "declined_chats": "Abandoned Chats",
    "avg_handle_time": "Average Handle Time",
    "group_chats": "Group Chats Engaged In",
    "agents_logged_in": "Agents Logged In",
    "avg_interactions": "Average Interactions Per Chat",
    "avg_wait_time": "Average Customer Wait Time"
}

TABLE_COUNT_RECORD_DATA = {
    "chats_raised": {
        "1": "9",
        "2": "33",
        "3": "22",
        "4": "102",
        "5": "12"
    },
    "chats_resolved": {
        "1": "8",
        "2": "28",
        "3": "20",
        "4": "90",
        "5": "11"
    },
    "abandoned_chats": {
        "1": "1",
        "2": "5",
        "3": "2",
        "4": "12",
        "5": "1"
    },
    "offline_chats": {
        "1": "2",
        "2": "3",
        "3": "2",
        "4": "20",
        "5": "3"
    },
    "declined_chats": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    },
    "avg_handle_time": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    },
    "group_chats": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    },
    "agents_logged_in": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    },
    "avg_interactions": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    },
    "avg_wait_time": {
        "1": "5",
        "2": "20",
        "3": "10",
        "4": "80",
        "5": "7"
    }
}

TABLE_CHANNEL_RECORD_DATA = {
    "chats_raised": {
        "Android": "9",
        "Alexa": "33",
        "Facebook": "22",
        "GoogleHome": "102",
        "WhatsApp": "12",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "22",
        "Voice": "11",
        "Email": "4",
        "Viber": "7"
    },
    "chats_resolved": {
        "Android": "8",
        "Alexa": "28",
        "Facebook": "20",
        "GoogleHome": "90",
        "WhatsApp": "11",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "19",
        "ET-Source": "29",
        "Twitter": "5",
        "Instagram": "42",
        "GoogleRCS": "24",
        "Voice": "14",
        "Email": "18",
        "Viber": "9",
    },
    "abandoned_chats": {
        "Android": "1",
        "Alexa": "5",
        "Facebook": "2",
        "GoogleHome": "12",
        "WhatsApp": "1",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "19",
        "ET-Source": "13",
        "Twitter": "7",
        "Instagram": "4",
        "GoogleRCS": "22",
        "Voice": "11",
        "Email": "7",
        "Viber": "3",
    },
    "offline_chats": {
        "Android": "2",
        "Alexa": "3",
        "Facebook": "2",
        "GoogleHome": "20",
        "WhatsApp": "3",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "30",
        "Voice": "21",
        "Email": "14",
        "Viber": "2",
    },
    "declined_chats": {
        "Android": "1",
        "Alexa": "5",
        "Facebook": "2",
        "GoogleHome": "12",
        "WhatsApp": "1",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "16",
        "ET-Source": "18",
        "Twitter": "15",
        "Instagram": "6",
        "GoogleRCS": "7",
        "Voice": "18",
        "Email": "14",
        "Viber": "6",
    },
    "avg_handle_time": {
        "Android": "9",
        "Alexa": "33",
        "Facebook": "22",
        "GoogleHome": "102",
        "WhatsApp": "12",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "22",
        "Voice": "11",
        "Email": "18",
        "Viber": "20",
    },    
    "avg_wait_time": {
        "Android": "9",
        "Alexa": "33",
        "Facebook": "22",
        "GoogleHome": "102",
        "WhatsApp": "12",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "22",
        "Voice": "11",
        "Email": "13",
        "Viber": "17",
    },
    "group_chats": {
        "Android": "1",
        "Alexa": "5",
        "Facebook": "2",
        "GoogleHome": "12",
        "WhatsApp": "1",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "22",
        "Voice": "11",
        "Email": "18",
        "Viber": "9",
    },
    "agents_logged_in": {
        "Android": "9",
        "Alexa": "33",
        "Facebook": "22",
        "GoogleHome": "102",
        "WhatsApp": "12",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "79",
        "ET-Source": "17",
        "Twitter": "7",
        "Instagram": "67",
        "GoogleRCS": "25",
        "Voice": "4",
        "Email": "8",
        "Viber": "11",
    },
    "avg_interactions": {
        "Android": "2",
        "Alexa": "3",
        "Facebook": "2",
        "GoogleHome": "20",
        "WhatsApp": "3",
        "GoogleBusinessMessages": "13",
        "Telegram": "10",
        "Microsoft": "1",
        "Web": "10",
        "iOS": "9",
        "ET-Source": "22",
        "Twitter": "15",
        "Instagram": "45",
        "GoogleRCS": "15",
        "Voice": "18",
        "Email": "16",
        "Viber": "10",
    }
}

DOWNLOAD_REPORTS_MAP = {
    "performance_report": "Performance Report",
    "analytical_report": "Combined Analytical Report",
    "customer_report": "Customer Centric Report",
}

DOWNLOAD_REPORTS_DATA = {
    "performance_report": "/files/email-profile-sample-files/performance_report_sample.xls",
    "analytical_report": "/files/email-profile-sample-files/analytical_report_sample.xls",
    "customer_report": "/files/email-profile-sample-files/customer_report_sample.xls",
}
