from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

from EasyAssistApp import views
from EasyAssistApp import job_scheduler
from . import views_cognomeet as vd
from . import views_analytics_outbound
from . import views_analytics_reverse
from . import views_extension as ve
from . import views_proxy as vp
from . import views_proxy_analytics_outbound
from . import views_canned_responses

urlpatterns = [
    url(r'^$', views.EasyAssistHomePage, name="easy-assist-home-page"),
    # Demo Link
    url(r'^demo/$', views.EasyAssistDemo, name="demo-page"),
    url(r'^icici-bank-demo/$', views.ICICIBankDemo, name="icici-bank-demo-page"),
    url(r'^sbi-mf-demo/$', views.SBIMFDemo, name="sbi-mf-demo-page"),
    url(r'^general-insurance/$', views.WesternGeneralInsurance,
        name="general-insurance"),
    url(r'^cams-demo/$', views.CamsDemo),
    ##########################################################################
    # url(r'^login/$', views.SalesAILoginPage, name="agent-login-page"),
    url(r'^logout/$', views.LogoutAPI, name="logout-api"),
    url(r'^authentication/$', views.AgentAuthentication,
        name="agent-authentication-api"),
    url(r'^get-captcha/$', views.GetCaptcha),
    url(r'^forgot-password/$', views.CobrowseForgotPassword),
    url(r'^verify-forgot-password/$', views.AgentResetPassword),
    url(r'^session-validation/$', views.CobrowsingAppSessionValidation),
    url(r'^session-validation/expert/$',
        views.CobrowsingAppSessionValidationExpert),
    url(r'^access-denied/$', views.CobrowsingAppSessionAccessDenied),
    url(r'^session-closed/$', views.CobrowsingAppSessionEnded),
    #########################################################################
    # [ProxyPassServer]
    url(r'^files/<path:address>', views.ProxyPass),
    #################### Polling and Pushing
    # Sales.AI Dashboard
    # url(r'^sales-ai/login/$', views.SalesAILoginPage, name="sales-ai-page"),
    url(r'^sales-ai/dashboard/$', views.SalesAIDashboard, name="sales-dashboard"),
    url(r'^sales-ai/request-queue-dashboard/$', views.SalesAIQueueDashboard, name="request-queue-dashboard"),
    url(r'^sales-ai/settings/canned_response-dashboard/$', views_canned_responses.CannedResponseDashboard),
    url(r'^sales-ai/support-history/$',
        views.SalesSupportHistory, name="sales-support-history"),
    url(r'^sales-ai/sales-meetings/$',
        views.SalesMeetings, name="sales-meetings"),
    url(r'^sales-ai/meeting-audit-trail/$',
        vd.CognoVidAuditTrail, name="meeting-audit-trail/"),
    url(r'^sales-ai/unattended-leads/$',
        views.UnattendedLeadsDetails, name="unattended-leads/"),
    url(r'^sales-ai/declined-leads/$',
        views.DeclinedLeadsDetails, name="declined-leads/"),
    url(r'^sales-ai/followup-leads/$',
        views.FollowUpLeadsDetails, name="followup-leads/"),
    url(r'^sales-ai/manually-converted-leads/$',
        views.ManuallyConvertedLeadsDetails, name="manually-converted-leads/"),
    url(r'^sales-ai/export-support-history/$',
        views.ExportSalesSupportHistory, name="export-support-history"),
    url(r'^sales-ai/export-unattended-leads-details/$',
        views.ExportUnattentedLeadsDetals, name="export-unattended-leads-details"),
    url(r'^sales-ai/export-declined-leads-details/$',
        views.ExportDeclinedLeadsDetals, name="export-declined-leads-details"),
    url(r'^sales-ai/export-followup-leads-details/$',
        views.ExportFollowUpLeadsDetals, name="export-followup-leads-details"),
    url(r'^sales-ai/export-manually-converted-leads-details/$',
        views.ExportManuallyConvertedLeads, name="export-manually-converted-leads-details"),
    url(r'^sales-ai/export-meeting-support-history/$',
        views.ExportMeetingSupportHistory, name="export-meeting-support-history"),
    url(r'^sales-ai/export-screen-recording-history/$',
        views.ExportScreenRecordingHistory, name="export-screen-recording-history"),
    url(r'^sales-ai/export-audit-trail-details/$',
        views.ExportAuditTrailDetals, name="export-audit-trail-details"),
    url(r'^sales-ai/export-agent-audit-trail-details/$',
        views.ExportAgentAuditTrailDetals, name="export-agent-audit-trail-details"),
    url(r'^sales-ai/export-agent-online-audit-trail-details/$',
        views.ExportAgentOnlineAuditTrailDetals, name="export-agent-online-audit-trail-details"),
    url(r'^sales-ai/export-inbound-analytics/$',
        views.ExportInboundAnalytics, name="export-inbound-analytics"),
    url(r'^sales-ai/export-outbound-analytics/$',
        views_analytics_outbound.ExportOutboundAnalytics, name="export-outbound-analytics"),
    url(r'^sales-ai/export-reverse-analytics/$',
        views_analytics_reverse.ExportReverseAnalytics, name="export-reverse-analytics"),
    url(r'^sales-ai/export-general-analytics/$',
        views.ExportGeneralAnalytics, name="export-general-analytics"),
    url(r'^sales-ai/analytics/$',
        views.SalesAnalyticsDashboard, name="sales-analytics"),
    url(r'^sales-ai/cogno-meet-analytics/$',
        views.CognoMeetAnalyticsDashboard, name="sales-cogno-meet-analytics"),
    url(r'^sales-ai/analytics-outbound/$',
        views.SalesAnalyticsOutboundDashboard, name="sales-analytics-outbound"),
    url(r'^sales-ai/access-management/$',
        views.SalesAccessManagement, name="sales-access-management"),
    url(r'^sales-ai/customer-support-documents/',
        views.CustomerSupportDocuments, name="customer-support-documents"),
    url(r'^sales-ai/upload-customer-support-files/',
        views.UploadCustomerSupportDocuments, name="upload-customer-support-files"),
    url(r'^sales-ai/update-support-document-detail/$',
        views.UpdateSupportDocumentDetail, name="update-support-document-detail"),
    url(r'^sales-ai/delete-support-document/$',
        views.DeleteSupportDocument, name="delete-support-document"),
    url(r'^sales-ai/upload-cobrowser-logo/$',
        views.UploadCobrowserLogo, name="upload-cobrowser-logo"),
    url(r'^sales-ai/delete-cobrowser-logo/$',
        views.DeleteCobrowserLogo, name="delete-cobrowser-logo"),
    url(r'^sales-ai/upload-connect-with-agent-icon/$',
        views.UploadConnectWithAgentIcon, name="upload-connect-with-agent-icon"),
    url(r'^sales-ai/support-history/last-state/(?P<session_id>[a-zA-Z0-9-_]+)',
        views.RenderLastStateOfCobrowsingSession, name="last-state-page"),
    # Settings Urls
    url(r'^sales-ai/agent/profile/settings/$', views.SalesAgentProfileSettings,
        name="sales-settings-agent-page"),
    url(r'^sales-ai/settings/$', views.SalesAnalyticsSettings,
        name="sales-settings-agent-home-page"),
    url(r'^sales-ai/settings/admin-profile/$', views.SalesAdminProfileSettings,
        name="sales-settings-admin-profile"),
    url(r'^sales-ai/settings/integrations/$', views.SalesIntegrationSettings,
        name="sales-settings-integrations"),
    url(r'^sales-ai/settings/chrome-extension/$', views.SalesChromeExtensionSettings,
        name="sales-settings-chrome-extension"),
    url(r'^sales-ai/settings/advanced-settings/$', views.SalesAdvancedSettings,
        name="sales-settings-advanced"),
    url(r'^sales-ai/settings/options/$', views.SalesSettingsOptions,
        name="sales-settings-options"),
    url(r'^sales-ai/settings/options/general/$', views.SalesGeneralOptionsSettings,
        name="sales-settings-options-general"),
    url(r'^sales-ai/settings/options/general/agent-settings-general/$', views.SalesGeneralAgentSettings,
        name="sales-settings-options-general-agent-settings"),
    url(r'^sales-ai/settings/options/general/admin-settings-general/$', views.SalesGeneralAdminSettings,
        name="sales-settings-options-general-admin-settings"),
    url(r'^sales-ai/settings/options/general/customer-side-settings/$', views.SalesGeneralCustomerSettings,
        name="sales-settings-options-general-customer-side-settings"),
    url(r'^sales-ai/settings/options/general/console-settings/$', views.SalesGeneralConsoleSettings,
        name="sales-settings-options-general-console-settings"),
    url(r'^sales-ai/settings/options/cobrowse/$', views.SalesCobrowseSettings,
        name="sales-settings-options-cobrowse"),
    url(r'^sales-ai/settings/options/cobrowse/agent/$', views.SalesCobrowseAgentSettings,
        name="sales-settings-options-cobrowse-agent"),
    url(r'^sales-ai/settings/options/cobrowse/admin/$', views.SalesCobrowseAdminSettings,
        name="sales-settings-options-cobrowse-admin"),
    url(r'^sales-ai/settings/options/video-call/$', views.SalesVideoCallSettings,
        name="sales-settings-options-video-call"),
    url(r'^sales-ai/settings/options/video-call/agent/$', views.SalesVideoCallAgentSettings,
        name="sales-settings-options-video-call-agent"),
    url(r'^sales-ai/settings/options/video-call/admin/$', views.SalesVideoCallAdminSettings,
        name="sales-settings-options-video-call-admin"),
    url(r'^sales-ai/settings/options/calendar/$', views.SalesCalendarSettings,
        name="sales-settings-options-calendar"),
    url(r'^sales-ai/settings/options/cobrowse/general/$', views.SalesCobrowseGeneralSettings,
        name="sales-settings-options-cobrowse-general"),
    url(r'^sales-ai/settings/options/cobrowse/customer/$', views.SalesCobrowseCustomersSettings,
        name="sales-settings-options-cobrowse-customer"),
    url(r'^sales-ai/settings/email-analytics-settings/$', views.SalesEmailAnalyticsSettings,
        name="sales-settings-email-analytics-settings-page"),
    url(r'^sales-ai/advanced-settings/static/$', views.SalesAdvancedSettingsStatic,
        name="sales-advanced-settings-static-page"),
    url(r'^sales-ai/advanced-settings/assigntask/$', views.SalesAdvancedSettingsAssignTask,
        name="sales-advanced-settings-assigntask-page"),
    url(r'^sales-ai/advanced-settings/logs/$', views.SalesAdvancedSettingsLogs,
        name="sales-advanced-settings-logs-page"),
    url(r'^sales-ai/advanced-settings/crm/$', views.SalesAdvancedSettingsCRM,
        name="sales-advanced-settings-crm-page"),
    url(r'^sales-ai/advanced-settings/api-integration/$', views.SalesAdvancedSettingsAPIIntegration,
        name="sales-advanced-settings-api-integration-page"),
    url(r'^sales-ai/update-log-file/$', views.UpdateLogFile),
    url(r'^sales-ai/download-log-file/$', views.DownloadEasyAssistLogFile),
    url(r'^sales-ai/audit-trail/$', views.SalesAuditTrail),
    url(r'^sales-ai/agent-audit-trail/$', views.SalesAgentAuditTrail),
    url(r'^sales-ai/agent-online-audit-trail/$', views.SalesAgentOnlineAuditTrail),
    url(r'^sales-ai/livechat/$', views.SalesAILiveChatWindow),
    url(r'^sales-ai/screen-recording-audit-trail/$',
        views.ScreenRecordingAuditTrail),
    url(r'^sales-ai/cobrowse-video-conferencing-form/$', views.CobrowseForms),
    url(r'^sales-ai/cobrowse-video-conferencing-form/create/$',
        views.CreateCobrowseForms),
    url(
        r'^sales-ai/cobrowse-video-conferencing-form/edit/(?P<form_id>[0-9]+)$', views.EditCobrowseForms),
    url(r'^sales-ai/create-cobrowse-form/$', views.AddNewCobrowseForm),
    url(r'^sales-ai/save-cobrowse-form/$', views.SaveCobrowseForm),
    url(r'^sales-ai/change-cobrowse-form-agent/$', views.ChangeCobrowseFormAgent),
    url(r'^sales-ai/delete-video-conferencing-form/$',
        views.DeleteVideoConferencingForm),
    url(r'^sales-ai/delete-cobrowse-form-category/$',
        views.DeleteCobrowseFormCategory),
    url(r'^sales-ai/delete-cobrowse-form-category-question/$',
        views.DeleteCobrowseFormCategoryQuestion),
    url(r'^sales-ai/upload-chat-bubble-icon/$',
        views.UploadChatBubbleIcon, name="upload-chat-bubble-icon"),
    url(r'^sales-ai/reset-chat-bubble-icon/$',
        views.ResetChatBubbleIcon, name="reset-chat-bubble-icon"),
    url(r'^sales-ai/save-inactivity-pop-up-urls/$', views.SaveInactivityPopupURLs),
    url(r'^sales-ai/save-exit-intent-pop-up-urls/$',
        views.SaveExitIntentPopupURLs),
    url(r'^save-cognomeet-access-token/$',
        views.SaveCognoMeetAccessToken),
        

    # Client Side Sync Data
    url(r'^sales-ai.html$', views.SalesAIIframePage),
    url(r'^create-token/$', views.CobrowseIOCreateToken),
    url(r'^sync/$', views.SyncCobrowseIO),
    url(r'^highlight/$', views.HighlightCheckCobrowseIO),
    url(r'^initialize/$', views.CobrowseIOInitialize),
    url(r'^initialize-using-droplink/$', views.CobrowseIOInitializeUsingDroplink),
    url(r'^initiate-droplink-session/$', views.InitiateDropLinkSession),
    url(r'^save-non-working-hour-customer-details/$',
        views.SaveNonWorkingHourCurstomerDetail),
    url(r'^close-session/$', views.CobrowseIOCloseSession),
    url(r'^capture-client-screen/$', views.CobrowseIOCaptureClientScreen),
    url(r'^capture-lead/$', views.CobrowseIOCaptureLead),
    url(r'^submit-client-feedback/$', views.SubmitClientFeedback),
    url(r'^mark-lead-as-converted/$', views.MarkLeadAsConverted),
    url(r'^update-agent-assistant-request/$',
        views.UpdateAgentAssistantRequest),
    url(r'^update-agent-meeting-request/$',
        views.UpdateAgentMeetingRequest),
    url(r'^fetch-connected-agent-details/$',
        views.FetchConnectedAgentDetails),
    url(r'^client-authentication/$', views.ClientAuthentication),
    url(r'^save-system-audit/$', views.SaveSystemAuditTrail),
    url(r'^agent-online-audit-trail/$', views.AgentOnlineAuditTrail),
    url(r'^sales-ai/client/livechat/$', views.SalesAIClientLiveChatWindow),
    url(r'^set-easyassist-customer/$', views.EasyAssistCustomerSet),
    url(r'^customer/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.CobrowseIOClientPage),
    url(r'^available-agent-list/', views.AvailableAgentList),
    url(r'^download-file/(?P<file_key>[a-zA-Z0-9-_]+)/$', views.FileAccess),
    url(r'^view-file/(?P<file_key>[a-zA-Z0-9-_]+)/$', views.ViewFile),
    url(r'^get-cobrowsing-chat-history/$', views.GetClientCobrowsingChatHistory),
    url(r'^report-bug/$', views.EasyAssistReportBug),
    url(r'^customer/request-assist-meeting/$', views.CustomerRequestCobrowsingMeeting),
    url(r'^client/check-meeting-status/$', views.CheckClientMeetingStatus),
    # Agent Side Sync Data
    url(r'^agent/(?P<session_id>[a-zA-Z0-9-_]+)$', views.CobrowseIOAgentPage),
    url(r'^agent/sync/$', views.SyncCobrowseIOAgent),
    url(r'^agent/check-cobrowsing-status/$', views.CheckCobrowsingStatus),
    url(r'^agent/highlight/$', views.SyncHighlightCobrowseIOAgent),
    url(r'^agent/take-client-screenshot/$', views.TakeClientScreenshot),
    url(r'^archive/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.ArchiveCobrowsingLead),
    url(r'^update-customer-meeting-request/$',
        views.UpdateCustomerMeetingRequest),
    url(r'^agent/change-active-status/$', views.ChangeAgentActiveStatus),
    url(r'^agent/close-session/$', views.CloseCobrowsingSession),
    url(r'^agent/manually-convert-lead/$', views.ManuallyConvertLead),
    url(r'^agent/check-lead-manually-converted/$', views.CheckLeadManuallyConverted),
    url(r'^agent/share-session/$', views.ShareCobrowsingSession),
    url(r'^agent/get-meta-information/$', views.GetCobrowsingMetaInformation),
    url(r'^agent/save-details/$', views.SaveAgentDetails),
    url(r'^agent/save-cobrowse-agent-advanced-details/$',
        views.SaveCobrowseAgentAdvancedDetails),
    url(r'^agent/add-new-agent/$', views.AddNewAgentDetails),
    url(r'^agent/update-agent-details/$', views.UpdateAgentDetails),
    url(r'^agent/delete-cobrowse-agent/$', views.DeleteCobrowseAgent),
    url(r'^agent/upload-user-details/$', views.UploadUserDetails),
    url(r'^agent/export-user-details/$', views.ExportUserDetails),
    url(r'^agent/export-supervisor-details/$', views.ExportSupervisorDetails),
    url(r'^agent/download-user-details-excel-template/$',
        views.DownloadUserDetailsTemplate),
    url(r'^agent/resend-account-password/$', views.ResendAccountPassword),
    url(r'^agent/update-active-agents-details/$', views.UpdateActiveAgentsDetails),
    url(r'^agent/toggle-agent-status/$', views.ToggleAgentStatus),
    url(r'^agent/get-agents-for-followup-lead-transfer/$', views.GetAgentsFollowupLeadTransfer),
    url(r'^agent/transfer-followup-leads-to-agent/$', views.TransferFollowupLeadsToAgent),
    url(r'^agent/save-cobrowsing-meta-details/cobrowsing/$',
        views.SaveCobrowsingMetaDetailsCobrowsing),
    url(r'^agent/save-cobrowsing-meta-details/cobrowsing/customer/$',
        views.SaveCobrowsingMetaCustomerDetailsCobrowsing),
    url(r'^agent/save-cobrowsing-meta-details/meeting/$',
        views.SaveCobrowsingMetaDetailsMeeting),
    url(r'^agent/save-cobrowsing-meta-details/general/$',
        views.SaveCobrowsingMetaDetailsGeneral),
    url(r'^agent/save-general-agent-settings/$',
        views.SaveGeneralAgentSettings),
    url(r'^agent/save-general-admin-settings/$',
        views.SaveGeneralAdminSettings),
    url(r'^agent/save-general-console-settings/$',
        views.SaveGeneralConsoleSettings),    
    url(r'^agent/save-cobrowse-agent-settings/$',
        views.SaveCobrowseAgentSettings),
    url(r'^agent/save-cobrowse-admin-settings/$',
        views.SaveCobrowseAdminSettings),
    url(r'^agent/save-cobrowse-general-settings/$',
        views.SaveCobrowseGeneralSettings),
    url(r'^agent/save-video-agent-settings/$',
        views.SaveVideoAgentSettings),
    url(r'^agent/save-video-admin-settings/$',
        views.SaveVideoAdminSettings),
    url(r'^agent/save-cobrowsing-meta-details/general/customer/$',
        views.SaveCobrowsingMetaCustomerDetailsGeneral),
    url(r'^agent/reset-cobrowsing-meta-details/$',
        views.ResetCobrowsingMetaDetails),
    url(r'^agent/add-new-obfuscated-field/$', views.AddNewObfuscatedField),
    url(r'^agent/edit-obfuscated-field/$', views.EditObfuscatedField),
    url(r'^agent/delete-obfuscated-fields/$', views.DeleteObfuscatedFields),
    url(r'^agent/add-new-search-tag-field/$', views.AddNewLeadHTMLField),
    url(r'^agent/edit-search-tag-field/$', views.EditLeadHTMLField),
    url(r'^agent/delete-search-tag-fields/$', views.DeleteLeadHTMLFields),
    url(r'^agent/add-new-auto-fetch-field/$', views.AddNewAutoFetchField),
    url(r'^agent/edit-auto-fetch-field/$', views.EditAutoFetchField),
    url(r'^agent/delete-auto-fetch-fields/$', views.DeleteAutoFetchFields),
    url(r'^agent/save-agent-comments/$', views.SaveAgentComments),
    url(r'^agent/search-lead/$', views.SearchCobrowsingLead),
    url(r'^agent/assign-lead/$', views.AssignCobrowsingLead),
    url(r'^agent/supervisor-assign-lead/$',
        views.SupervisoAssignCobrowsingLead),
    url(r'^agent/assign-queue-lead/$',
        views.AssignAgentCobrowsingLead),
    url(r'^agent/assign-cobrowsing-session/$', views.AssignCobrowsingSession),
    url(r'^agent/self-assign-cobrowsing-session/$', views.SelfAssignCobrowsingSession),
    url(r'^agent/transfer-cobrowsing-session/$', views.TransferCobrowsingSession),
    url(r'^agent/update-transfer-session-log/$', views.UpdateTransferCobrowsingSessionLogs),
    url(r'^agent/check-transfer-session-log/$', views.GetTransferCobrowsingSessionLogsUpdate),
    url(r'^agent/request-assist/$', views.RequestCobrowsing),
    url(r'^agent/request-assist-meeting/$', views.RequestCobrowsingMeeting),
    url(r'^agent/check-meeting-status/$', views.CheckMeetingStatus),
    url(r'^agent/mark-inactive/$', views.MarkLeadInactive),
    url(r'^agent/change-agent-activate-status/$',
        views.ChangeAgentActivateStatus),
    url(r'^agent/save-cobrowsing-chat/$', views.SaveCobrowsingChat),
    url(r'^agent/get-cobrowsing-chat-history/$', views.GetCobrowsingChatHistory),
    url(r'^agent/get-support-agents/$', views.GetListOfSupportAgents),
    url(r'^agent/get-support-material/$', views.GetSupportMaterialAgent),
    url(r'^agent/export/(?P<meta_data_pk>\d+)/$', views.ExportCapturedData),
    url(r'^agent/save-document/$', views.SaveDocument),
    url(r'^agent/save-multiple-document/$', views.SaveMultipleDocument),
    url(r'^agent/generate-drop-link/$', views.GenerateDropLink),
    url(r'^agent/switch-agent-mode/$', views.SwitchAgentMode),
    url(r'^agent/get-cobrowse-agent-comments/$',
        views.GetCobrowsingAgentComments),
    url(r'^sales-ai/upload-agent-profile-picture/$',
        views.UploadAgentPicture, name="upload-agent-profile-picture"),
    url(r'^sales-ai/delete-agent-profile-picture/$',
        views.DeleteAgentProfilePicture, name="delete-agent-profile-picture"),
    url(r'^sales-ai/check-malicious-agent-profile-picture/$',
        views.MalicioustProfilePicture, name="check-malicious-agent-profile-picture"),
    url(r'^agent/generate-video-meeting/$',
        vd.GenerateVideoConferencingMeet),
    url(r'^agent/get-system-audit-trail-basic-activity/$',
        views.GetSystemAuditTrailBasicActivity),
    # url(r'^agent/check-notification/$',views.CheckNotification),
    url(r'^agent/set-notification-for-agent/$',
        views.SetNotificationForAgent),
    url(r'^agent/get-lead-status/$', views.GetLeadStatus),
    url(r'^agent/get-all-active-lead-status/$', views.GetAllActiveLeadStatus),
    url(r'^agent/get-all-active-lead-count/$', views.GetAllActiveLeadCount),
    url(r'^agent/get-all-active-queue-status/$', views.GetAllActiveQueueStatus),
    url(r'^agent/check-customer-initiate-meeting-status/$', views.CustomerInitiateMeetingStatus),

    # Mailer analytics
    url(r'^agent/save-enable-email-settings/$', views.SaveEnableEmailSettings),
    url(r'^agent/save-email-analytics-profile/$', views.SaveEmailAnalyticsProfile),
    url(r'^agent/get-all-email-analytics-profiles/$', views.GetEmailAnalyticsProfiles),
    url(r'^agent/delete-email-analytics-profile/$', views.DeleteEmailAnalyticsProfile),
    url(r'^agent/trigger-email-analytics/$', views.TriggerEmailAnalytics),

    # Inbound Analytics
    url(r'^agent/basic-analytics/$', views.GetAgentBasicAnalytics),
    url(r'^agent/service-request-analytics/$',
        views.GetAgentServiceRequestAnalytics),
    url(r'^agent/agent-wise-request-analytics/$',
        views.GetAgentWiseRequestAnalytics),
    url(r'^agent/agent-wise-nps-analytics/$', views.GetAgentNPSAnalytics),
    url(r'^agent/query-page-analytics/$', views.GetQueryPageAnalytics),
    url(r'^agent/get-visited-page-title-list/$', views.GetVisitedPageTitleList),
    url(r'^agent/query-page-analytics-count/$',
        views.GetQueryPageAnalyticsCount),
    url(r'^agent/export-not-initiated-customer-details/$',
        views.ExportNotInitiatedCustomerDetails),
    url(r'^agent/export-conversions-by-url/$',
        views.ExportConversionsByURL),
    url(r'^agent/export-unique-customers-inbound/$',
        views.ExportInboundUniqueCustomers, name="export-unique-customers-inbound"),
    url(r'^agent/export-repeated-customers-inbound/$',
        views.ExportInboundRepeatedCustomers, name="export-repeated-customers-inbound"),
    url(r'^agent/export-cron-request-unique-customers-inbound/$',
        views.ExportCronRequestUniqueCustomersInbound, name="export-cron-request-unique-customers-inbound"),
    url(r'^agent/export-cron-request-repeated-customers-inbound/$',
        views.ExportCronRequestRepeatedCustomersInbound, name="export-cron-request-repeated-customers-inbound"),
    url(r'^agent/download-generated-links/$',
        views.DownloadGeneratedLinks, name="download-generated-links"),
    url(r'^agent/export-generated-links/$',
        views.ExportGeneratedDropLinks, name="export-generated-links"),

    # Cogno Meet Analytics
    url(r'^agent/cogno-meet-basic-analytics/$',
        views.GetCognoMeetBasicAnalytics),
    url(r'^agent/cogno-meet-analytics/$', views.GetCognoMeetAnalytics),
    url(r'^agent/cogno-meet-daily-time-trend-analytics/$',
        views.GetCognoMeetDailyTimeTrendAnalytics),
    url(r'^agent/cogno-meet-agent-wise-analytics/$',
        views.GetAgentWiseCognoMeetAnalytics),
    url(r'^agent/cogno-meet-cobrowse-video-analytics/$',
        views.GetCognoMeetCobrowsingAnalytics),

    # Outbound Analytics
    url(r'^agent/basic-analytics-outbound/$',
        views_analytics_outbound.GetAgentBasicAnalyticsOutbound),
    url(r'^agent/service-request-analytics-outbound/$',
        views_analytics_outbound.GetAgentServiceRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-request-analytics-outbound/$',
        views_analytics_outbound.GetAgentWiseRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-nps-analytics-outbound/$',
        views_analytics_outbound.GetAgentNPSAnalyticsOutbound),
    url(r'^agent/query-page-analytics-outbound/$',
        views_analytics_outbound.GetQueryPageAnalyticsOutbound),
    url(r'^agent/get-visited-page-title-list-outbound/$',
        views_analytics_outbound.GetVisitedPageTitleListOutbound),
    url(r'^agent/export-unique-customers-outbound/$',
        views_analytics_outbound.ExportUniqueCustomersOutbound, name="export-unique-customers-outbound"),
    url(r'^agent/export-repeated-customers-outbound/$',
        views_analytics_outbound.ExportRepeatedCustomersOutbound, name="export-repeated-customers-outbound"),
    url(r'^agent/export-cron-request-unique-customers-outbound/$',
        views_analytics_outbound.ExportCronRequestUniqueCustomersOutbound, name="export-cron-request-unique-customers-outbound"),
    url(r'^agent/export-cron-request-repeated-customers-outbound/$',
        views_analytics_outbound.ExportCronRequestRepeatedCustomersOutbound, name="export-cron-request-repeated-customers-outbound"),
    url(r'^agent/export-captured-leads/$',
        views_analytics_outbound.ExportCapturedLeads),
    url(r'^agent/email-captured-leads/$',
        views_analytics_outbound.EmailCapturedLeads),

    # Outbound Proxy Analytics
    url(r'^agent/basic-proxy-analytics-outbound/$',
        views_proxy_analytics_outbound.GetOutboundProxyAnalytics),
    url(r'^agent/service-proxy-request-analytics-outbound/$',
        views_proxy_analytics_outbound.GetAgentProxyServiceRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-proxy-request-analytics-outbound/$',
        views_proxy_analytics_outbound.GetAgentWiseProxyRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-proxy-nps-analytics-outbound/$',
        views_proxy_analytics_outbound.GetAgentNPSProxyAnalyticsOutbound),
    url(r'^agent/query-page-proxy-analytics-outbound/$',
        views_proxy_analytics_outbound.GetQueryPageProxyAnalyticsOutbound),
    url(r'^sales-ai/export-outbound-proxy-analytics/$',
        views_proxy_analytics_outbound.ExportOutboundProxyAnalytics, name="export-outbound-proxy-analytics"),
    
    # Reverse Analytics
    url(r'^sales-ai/reverse-analytics/$',
        views.SalesReverseAnalyticsDashboard, name="sales-reverse-analytics"),

    url(r'^agent/basic-analytics-reverse/$',
        views_analytics_reverse.GetReverseCobrowseBasicAnalytics),
    url(r'^agent/cobrowse-request-analytics-reverse/$',
        views_analytics_reverse.GetAgentCobrowseRequestAnalytics),
    url(r'^agent/agent-wise-request-analytics-reverse/$',
        views_analytics_reverse.GetAgentWiseRequestAnalyticsReverse),
    url(r'^agent/agent-wise-nps-analytics-reverse/$',
        views_analytics_reverse.GetAgentNPSAnalyticsReverse),
    url(r'^agent/query-page-analytics-reverse/$',
        views_analytics_reverse.GetQueryPageAnalyticsReverse),
    url(r'^agent/get-visited-page-title-list-reverse/$',
        views_analytics_reverse.GetVisitedPageTitleList),
    url(r'^agent/export-unique-customers-reverse/$',
        views_analytics_reverse.ExportReverseUniqueCustomers, name="export-unique-customers-reverse"),
    url(r'^agent/export-repeated-customers-reverse/$',
        views_analytics_reverse.ExportReverseRepeatedCustomers, name="export-repeated-customers-reverse"),
    url(r'^agent/export-cron-request-unique-customers-reverse/$',
        views_analytics_reverse.ExportCronRequestUniqueCustomersReverse, name="export-cron-request-unique-customers-reverse"),
    url(r'^agent/export-cron-request-repeated-customers-reverse/$',
        views_analytics_reverse.ExportCronRequestRepeatedCustomersReverse, name="export-cron-request-repeated-customers-reverse"),

    # Sandbox User
    url(r'^sandbox-user/creds/$', views.SandboxUserDashboard),
    url(r'^sandbox-user/create/$', views.CreateSandboxUser),
    url(r'^sandbox-user/get-all-users/$', views.GetAllSandboxUser),
    url(r'^sandbox-user/delete/$', views.DeleteSandboxUser),
    url(r'^sandbox-user/get-data/$', views.GetSandboxUserData),
    url(r'^sandbox-user/save/$', views.SaveSandboxUserData),
    url(r'^sandbox-user/update-expire-date/$', views.SandboxUserUpdateExpireDate),

    # Advanced Settings
    url(r'^agent/save-assign-task-processor-code/$',
        views.SaveAssignTaskProcessorCode),
    url(r'^agent/save-agent-details-api-processor-code/$',
        views.SaveAgentDetailsAPIProcessorCode),
    url(r'^agent/run-agent-details-api-processor-code/$',
        views.RunAgentDetailsAPIProcessorCode),
    url(r'^agent/fetch-static-file-list/', views.FetchStaticFileList),
    url(r'^agent/fetch-static-file-content/', views.FetchStaticFileContent),
    url(r'^agent/save-static-file-content/', views.SaveStaticFileContent),
    url(r'^agent/reset-static-file-content/', views.ResetStaticFileContent),
    url(r'^agent/get-static-file-save-audit-trail/$',
        views.GetStaticFileSaveAuditTrail),
    ###################################################################
    url(r'^app/client-authentication/$', views.AppClientAuthentication),
    url(r'^app/initialize/$', views.CobrowseAppCreateSession),
    url(r'^app/close-session/$', views.AppCloseCobrowsingSession),
    url(r'^app/submit-client-feedback/$', views.AppSubmitClientFeedback),
    url(r'^app/agent-update-cobrowse-io/$', views.AppAgentUpdateCobrowseIO),
    url(r'^app/save-document/$', views.AppSaveDocument),
    url(r'^app/save-cobrowsing-chat/$', views.AppSaveCobrowsingChat),
    url(r'^app/get-cobrowsing-chat-history/$',
        views.GetAppCobrowsingChatHistory),
    url(r'^app/get-cobrowsing-support-documents/$',
        views.GetCobrowsingSupportDocument),
    url(r'^app/client-status/$', views.AppClientStatusUpdate),
    url(r'^app/agent-status/$', views.AppAgentStatusUpdate),
    url(r'^app/save-client-cobrowsing-chat/$',
        views.AppClientSaveCobrowsingChat),
    url(r'^app/sync-customer-status/$', views.AppClientUpdateCobrowseIO),
    url(r'^app/update-agent-request-status/$',
        views.AppUpdateAgentAssistantRequest),
    url(r'^app/(?P<session_id>[a-zA-Z0-9-_]+)$', views.CobrowsingAppAgentPage),
    url(r'^app/schedule-meeting/$', views.AppScheduleMeeting),
    url(r'^app/capture-client-screen/$', views.AppCaptureClientScreen),
    url(r'^app/client-close-session/$', views.AppClientCloseSession),
    url(r'^app/save-recorded-video/$', views.AppRecordedSessionVideo),
    url(r'^app/get-captcha/$', views.GetAppCaptcha),
    url(r'^app/agent-authentication/$', views.AppAgentAuthentication),
    url(r'^app/meeting-lobby/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.CobrowsingAppMeetingLobby),
    url(r'^app/get-client-cobrowsing-chat-history/$',
        views.GetAppClientCobrowsingChatHistory),
    url(r'^app/get-available-agent-list/$',
        views.AppCobrowsingAvailableAgentList),
    url(r'^app/save-non-working-hour-customer-details/$',
        views.AppSaveNonWorkingHourCustomerDetail),
    ##################################################################
    ################################   CognoVid screen recording  ############
    url(r'^meeting/(?P<meeting_id>[a-zA-Z0-9-_]+)$', vd.CognoVidMeeting),
    url(r'^agent-cobrowse-meeting/(?P<session_id>[a-zA-Z0-9-_]+)$',
        vd.AgentCobrowseVideoMeeting),
    url(r'^client-cobrowse-meeting/(?P<session_id>[a-zA-Z0-9-_]+)$',
        vd.ClientCobrowseVideoMeeting),
    url(r'^meeting-ended/(?P<meeting_id>[a-zA-Z0-9-_]+)$',
        vd.CognoVidMeetingEnded),
    url(r'^scheduled-meetings/$', vd.CognoVidMeetingScheduled),
    url(r'^scheduled-meetings-list/$', vd.GetCognoVidScheduledMeetingsList),
    url(r'^authenticate-meeting-password/$', vd.CognoVidAuthenticatePassword),
    url(r'^save-meeting-duration/$', vd.CognoVidMeetingDuration),
    url(r'^save-meeting-notes/$', vd.CognoVidMeetingNotes),
    url(r'^save-meeting-chats/$', vd.CognoVidMeetingChats),
    url(r'^get-client-agent-chats/$', vd.CognoVidGetClientAgentChat),
    url(r'^save-screen-recorded-data/', vd.SaveScreenRecordedData),
    url(r'^save-agent-recorded-data/', vd.SaveAgentRecordedData),
    url(r'^upload-cognovid-file-attachment/', vd.UploadCognoVidFileAttachment),
    url(r'^get-meet-support-agents/$', vd.GetListOfMeetSuportAgents),
    url(r'^get-meeting-forms/$', vd.GetListOfMeetingForms),
    url(r'^get-meet-support-documents/$', vd.GetListOfMeetingSupportDocument),
    url(r'^request-agent-meeting/$', vd.RequestJoinMeeting),
    url(r'^agent/save-video-meeting/$', vd.SaveVideoConferencingMeet),
    url(r'^agent/assign-video-meeting/$', vd.AssignVideoConferencingMeet),
    url(r'^invite-video-meeting-email/$', vd.InviteVideoMeetingEmail),
    url(r'^save-cobrowsing-screen-recorded-data/$',
        views.SaveCobrowsingScreenRecordedData),
    url(r'^save-reverse-cobrowsing-screen-recorded-data/$',
        views.SaveReverseCobrowsingScreenRecordedData),
    url(r'^check-agent-connected-or-not/$', vd.CheckAgentConnectedOrNot),
    url(r'^update-agent-join-status/$', vd.UpdateAgentJoinStatus),
    url(r'^save-client-recorded-data/', vd.SaveClientRecordedData),
    url(r'^voip-meeting-status/', vd.GetVoipMeetingStatus),
    url(r'^save-client-location-details/', vd.SaveClientLocationDetails),
    url(r'^check-cobrowsing-meeting-status/', vd.CheckCobrowsingMeetingStatus),
    url(r'^save-meeting-screenshot/', vd.SaveCognoMeetScreenshot),
    url(r'^pageshot/(?P<pageshot_id>\d+)$', views.EasyAssistPageShot),
    url(r'^client-meeting-feedback/', vd.ClientMeetingFeedback),
    url(r'^check-meeting-ended-or-not/', vd.CheckMeetingEndedOrNot),
    url(r'^cobrowse-data-collect/(?P<meeting_id>[a-zA-Z0-9-_]+)/(?P<form_id>[0-9]+)/$',
        vd.CobrowseVideoConferencingDataCollect),
    url(r'^cobrowse-data-collect/show/(?P<meeting_id>[a-zA-Z0-9-_]+)/(?P<form_id>[0-9]+)/$',
        vd.ShowCobrowseDataCollectForm),
    url(r'^save-cobrowse-collected-form-data/$',
        vd.SaveCobrowseCollectedFormData),
    url(r'^download-meeting-recording/$',
        vd.DownloadMeetingRecording),
    url(r'^save-voip-meeting-duration/$', vd.SaveVoipMeetingDuration),
    url(r'^voip-meeting-ended/(?P<meeting_user>[a-z]+)/(?P<meeting_id>[a-zA-Z0-9-_]+)$', vd.VoIPMeetingEnded),
    url(r'^map-script/$', vd.LoadMapScript),
    url(r'^get-meeting-support-agents/$', vd.GetMeetingSupportAgent),
    url(r'^save-meeting-end-time/$', vd.SaveCognoVidMeetingEndTime),
    url(r'^save-jitsi-recording/$', vd.SaveJitsiRecording),
    url(r'^agent-under-supervisor/$', vd.GetListOfAgentUnderSupervisor),
    # Reverse Cobrowsing

    url(r'^reverse/initialize/$', views.CobrowseIOReverseInitialize),
    url(r'^client/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.CobrowseIOAgentReverserPage),
    url(r'^reverse/check-agent-status/$', views.CheckAgentReverseCobrowseStatus),
    url(r'^reverse/check-client-status/$',
        views.CheckClientReverseCobrowseStatus),
    url(r'^reverse/save-cobrowsing-chat/$', views.SaveReverseCobrowsingChat),
    url(r'^reverse/get-cobrowsing-chat-history/$',
        views.GetReverseCobrowsingChatHistory),
    url(r'^reverse/client-close-session/$',
        views.CloseReverseCobrowsingSession),
    url(r'^reverse/agent-close-session/$',
        views.CloseReverseAgentCobrowsingSession),
    url(r'^reverse/request-assist-meeting/$',
        views.RequestVoipMeeting),
    url(r'^reverse/check-meeting-status/$',
        views.CheckReverseCobrowsingMeetingStatus),
    url(r'^reverse/update-agent-meeting-request/$',
        views.UpdateReverseCobrowseMeetingRequest),
    url(r'^reverse/save-client-location/$',
        views.SaveClientLocation),
    url(r'^reverse/get-meta-information/$',
        views.GetCobrowsingMetaInformationReverse),
    url(r'^reverse/get-support-agents/$',
        views.GetListOfSupportAgentsReverse),
    url(r'^reverse/share-session/$',
        views.ShareCobrowsingSessionReverse),
    url(r'^reverse/sync-invited-agent-status/$',
        views.SyncInvitedAgentStatus),
    url(r'^reverse/close-session/$',
        views.CloseCobrowsingSessionReverse),
    url(r'^reverse/get-support-material/$',
        views.GetSupportMaterialAgentReverse),

    # Screen sharing cobrowse

    url(r'^screensharing-cobrowse/', views.EasyAssistScreensharingCobrowse),
    url(r'^agent/screensharing-cobrowse/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.CobrowseIDScreensharingPage),

    # PII data
    url(r'^send-masking-pii-data-otp/$', views.MaskingPIIDataOTP),
    url(r'^verify-masking-pii-data-otp/$', views.VerifyMaskingPIIDataOTP),
    url(r'^enable-masking-pii-data/$', views.EnableMaskingPIIData),

    ################# General Analytics ##############
    url(r'^sales-ai/general-analytics/$',
        views.SalesGeneralAnalyticsDashboard, name="sales-general-analytics"),
    url(r'^agent/get-general-visited-page-title-list/$',
        views.GetGeneralVisitedPageTitleList),
    url(r'^agent/general-analytics/$', views.GetGeneralAnalyticsDetails),

    ################# IDFC MOBILE DEMO ############
    url(r'^icici-demo/first/(?P<key>[a-zA-Z0-9-_]+)$', views.icici_demo_first),
    url(r'^idfc-demo/first/(?P<key>[a-zA-Z0-9-_]+)$', views.idfc_demo_first),
    url(r'^icici-demo/second/(?P<key>[a-zA-Z0-9-_]+)$',
        views.icici_demo_second),
    url(r'^cobrowsing-form-demo/(?P<key>[a-zA-Z0-9-_]+)$',
        views.cobrowsing_form_demo),
    url(r'^cobrowsing-form-demo/first/(?P<key>[a-zA-Z0-9-_]+)$',
        views.cobrowsing_form_demo_first),
    url(r'^cobrowsing-form-demo/second/(?P<key>[a-zA-Z0-9-_]+)$',
        views.cobrowsing_form_demo_second),

    ################# CRM Integration Apis ############
    url(r'^agent/generate-crm-api-documents/$', views.CRMGenerateAPIDocuments),
    url(r'^crm/auth-token/$',
        views.CRMGenerateAuthToken),
    url(r'^crm/inbound/$',
        views.CRMInboundIntegration),
    url(r'^crm/capture-lead/$', views.CRMCaptureLeadIntegration),
    url(r'^crm/search-lead/$',
        views.CRMSearchLeadIntegration),
    url(r'^crm/droplink/$',
        views.CRMDropLinkIntegration),
    url(r'^crm/cobrowsing/(?P<token>[a-zA-Z0-9-_]+)$',
        views.CRMCobrowsingAutoLogin),
    url(r'^crm/support-history/$',
        views.CRMCobrowsingSupportHistory),
    url(r'^crm/chat-history/$',
        views.CRMCobrowsingChatHistory),
    url(r'^crm/meeting/(?P<token>[a-zA-Z0-9-_]+)$',
        views.CRMCognoMeetAutoLogin),
    url(r'^crm/create-meeting/$',
        views.CRMCognoMeetCreateMeeting),
    url(r'^crm/delete-meeting/$',
        views.CRMCognoMeetDeleteMeeting),
    url(r'^crm/meeting-status/$',
        views.CRMCognoMeetMeetingStatus),
    url(r'^crm/meeting-details/$',
        views.CRMCognoMeetMeetingDetails),
    url(r'^download-crm-document/(?P<document_type>[a-zA-Z0-9-_]+)$',
        views.DownloadCRMDocuments),
    url(r'^crm/agent/add/$', views.CRMAgentAdd),
    url(r'^crm/agent/delete/$', views.CRMAgentDelete),
    url(r'^crm/agent/change-status/$', views.CRMAgentChangeStatus),
    url(r'^crm/agent/change-password/$', views.CRMAgentChangePassword),
    url(r'^crm/meeting/update-settings/$', views.CRMUpdateMeetingSettings),
    url(r'^crm/meeting/agent-meetings/$', views.CRMAgentMeetings),
    url(r'^crm/meeting/analytics/$', views.CRMMeetingAnalytics),

    ################### Agent Management APIs ###################

    url(r'^crm/generate-auth-token/$',
        views.CRMUserGenerateAuthToken),
    url(r'^crm/create-user/$', views.CRMCreateUser),
    url(r'^crm/update-user/$', views.CRMUpdateUser),
    url(r'^crm/change-user-status/$', views.CRMChangeUserStatus),
    url(r'^crm/get-user-status/', views.CRMUserStatus),
    url(r'^crm/get-all-users-status/', views.CRMAllUsersStatus),
    url(r'^crm/get-list-of-users/', views.CRMGetListOfUsers),
    url(r'^crm/change-user-password/$', views.CRMChangeUserPassword),

    ################### Chrome Extension ###################
    url(r'^extension-authentication/', ve.ExtensionAuthentication),
    url(r'^verify-extension-login/', ve.VerifyExtensionLogin),
    url(r'^verify-extension-token/', ve.VerifyExtensionToken),
    url(r'^save-extension/', ve.SaveExtension),
    url(r'^ext/update-agent-cobrowsing-details/$', ve.UpdateAgentCobrowsingDetails),
    url(r'^ext/generate-drop-link/$', ve.GenerateDropLink),
    url(r'^ext/search-lead/$', ve.SearchCobrowsingLead),
    url(r'^ext/assign-lead/$', ve.AssignCobrowsingLead),
    url(r'^ext/request-assist/$', ve.RequestCobrowsing),
    url(r'^ext/close-session/$', ve.CloseCobrowsingSession),

    ################### Cobrowse Calendar APIs ###################
    url(r'^add-holiday-calendar/$', views.AddHolidayCalendar),
    url(r'^create-working-hours/$', views.CreateWorkingHours),
    url(r'^edit-calendar-event/$', views.EditCalendarEvent),
    
    ################### Cobrowse Canned Response APIs ###############
    url(r'^get-all-canned-responses/$', views_canned_responses.GetAllCannedResponses),
    url(r'^create-new-canned-response/$', views_canned_responses.CreateNewCannedResponse),
    url(r'^create-new-canned-response-excel/$', views_canned_responses.CreateCannedResponseWithExcel),
    url(r'^upload-excel/$', views_canned_responses.EasyAssistAppUploadExcel),
    url(r'^edit-canned-response/$', views_canned_responses.EditCannedResponse),
    url(r'^delete-canned-response/$', views_canned_responses.DeleteCannedResponse),
    url(r'^sales-ai/export-canned-responses/$',
        views_canned_responses.ExportCannedResponses, name="export-canned_responses"),
    url(r'^agent/update-agent-used-canned-response/$', views_canned_responses.UpdateAgentCannedResponse),
    url(r'^reverse/update-agent-used-canned-response/$', views_canned_responses.UpdateAgentCannedResponseReverse),

    ################### LiveChat Cobrowse #######################
    url(r'^enable-livechat-cobrowse-settings/$', views.EnableLiveChatCobrowseSettings),
    url(r'^check-agent-exists/$', views.CheckCobrowseAgentExists),

    ################### Proxy Server Cobrowse #######################
    url(r'^cognoai-cobrowse/page-render/(?P<proxy_key>[a-zA-Z0-9-_]+)/(?P<url_path>.*)$', vp.RenderProxyRequest),
    url(r'^cognoai-cobrowse/$', vp.CognoAICobrowse),
    url(r'^cognoai-cobrowse/initialize/$', vp.InitializeProxySession),
    url(r'^cognoai-cobrowse/proxy-key/(?P<proxy_key>[a-zA-Z0-9-_]+)$', vp.ProxyCobrowseSession),
    url(r'^cognoai-cobrowse/start-proxy-cobrowsing/$', vp.StartProxyCobrowsing),
    url(r'^cognoai-cobrowse/add-new-proxy-session-tab/$', vp.AddNewProxySessionTab),
    url(r'^cognoai-cobrowse/proxy-cobrowsing-expired/$', vp.ProxyCobrowseSessionExpired),
    url(r'^cognoai-cobrowse/proxy-cobrowsing-end-page/$', vp.ProxyCobrowseSessionEnd),
    url(r'^proxy-cobrowsing-debug/$', vp.ProxyCobrowseDebug),
]

# Do not Use this scheduler in production
# job_scheduler.start()
