from django.urls import path
from django.conf import settings
from django.urls import re_path
from django.contrib import admin

from EasyAssistApp import views
from EasyAssistApp import job_scheduler

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.EasyAssistHomePage, name="easy-assist-home-page"),
    # Demo Link
    path('demo/', views.EasyAssistDemo, name="demo-page"),
    path('icici-bank-demo/', views.ICICIBankDemo, name="icici-bank-demo-page"),
    path('sbi-mf-demo/', views.SBIMFDemo, name="sbi-mf-demo-page"),
    path('general-insurance/', views.WesternGeneralInsurance,
         name="general-insurance"),
    path('cams-demo/', views.CamsDemo),
    ##########################################################################
    path('login/', views.SalesAILoginPage, name="agent-login-page"),
    path('logout/', views.LogoutAPI, name="logout-api"),
    path('authentication/', views.AgentAuthentication,
         name="agent-authentication-api"),
    path('get-captcha/', views.GetCaptcha),
    path('forgot-password/', views.CobrowseForgotPassword),
    path('verify-forgot-password/', views.AgentResetPassword),
    #########################################################################
    path('connect-agent/', views.ConnectToAgent, name="connect-agent-api"),
    path('sync-agent-screen/', views.SyncAgentScreen,
         name="sync-agent-screen-api"),
    path('sync-agent-screen-v2/', views.SyncAgentScreenV2,
         name="sync-agent-screen-api-v2"),
    path('client-disconnected/', views.ClientDisconnected,
         name='client-disconnected-api'),
    path('activate-highlight-element/', views.ActivateHighlightElement,
         name='activate-highlight-element-api'),
    path('deactivate-highlight-element/', views.DeactivateHighlightElement,
         name='deactivate-highlight-element-api'),
    path('check-highlighted-element/', views.CheckHighlightedElement,
         name="check-highlighted-element-api"),
    path('check-form-submit/', views.CheckFormSubmit,
         name="check-form-submit-api"),
    path('dashboard/', views.EasyAssistDashboard, name="dashboard"),
    path('settings/', views.SettingsPage, name="settings"),
    path('manage-forms/', views.ManageForms, name="manage-forms-page"),
    path('manage-fields/', views.ManageFields, name="manage-fields-page"),
    path('agent/assist/', views.AgentAssistance, name="agent-assistance"),
    path('agent/assist/v2/', views.AgentAssistanceV2, name="agent-assistance-v2"),
    path('marked-as-resolved/<uuid:screen_pk>',
         views.MarkAsResolved, name="mark-as-resolved-api"),
    path('request-assist/<uuid:screen_pk>',
         views.AgentAssistRequest, name="agent-assist-request-api"),
    path('check-agent-assistance-request/', views.CheckAgentAssistanceRequest,
         name="check-agent-assistance-request-api"),
    path('cancel-agent-assistance-request/', views.CancelAgentAssistanceRequest,
         name="cancel-agent-assistance-request-api"),
    path('auto-session-init/', views.AutoSessionInit,
         name="auto-session-init-api"),
    path('get-form-information/', views.GetFormInformation,
         name="get-form-information-api"),
    path('create-agent-assistance-request/', views.CreateAgentAssistanceRequest,
         name="create-agent-assistance-request-api"),
    ###########################################################################
    path('create-new-form/', views.CreateNewFormRequest,
         name="create-new-form-api"),
    path('create-new-field/', views.CreateNewFieldRequest,
         name="create-new-field-api"),
    # [ProxyPassServer]
    path('files/<path:address>', views.ProxyPass),
    #################### Polling and Pushing
    # Sales.AI Dashboard
    path('sales-ai/login/', views.SalesAILoginPage, name="sales-ai-page"),
    path('sales-ai/dashboard/', views.SalesAIDashboard, name="sales-dashboard"),
    path('sales-ai/support-history/', views.SalesSupportHistory,
         name="sales-support-history"),
    path('sales-ai/analytics/', views.SalesAnalyticsDashboard,
         name="sales-analytics"),
    path('sales-ai/access-management/', views.SalesAccessManagement,
         name="sales-access-management"),
    path('sales-ai/support-history/last-state/<uuid:session_id>',
         views.RenderLastStateOfCobrowsingSession, name="last-state-page"),
    path('sales-ai/settings/', views.SalesAnalyticsSettings,
         name="sales-settings-page"),
    path('sales-ai/audit-trail/', views.SalesAuditTrail),
    #################### Client Side Sync Data
    path('create-token/', views.CobrowseIOCreateToken),
    path('sync/', views.SyncCobrowseIO),
    path('highlight/', views.HighlightCheckCobrowseIO),
    path('initialize/', views.CobrowseIOInitialize),
    path('close-session/', views.CobrowseIOCloseSession),
    path('capture-client-screen/', views.CobrowseIOCaptureClientScreen),
    path('capture-lead/', views.CobrowseIOCaptureLead),
    path('submit-client-feedback/', views.SubmitClientFeedback),
    path('update-agent-assistant-request/', views.UpdateAgentAssistantRequest),
    path('client-authentication/', views.ClientAuthentication),
    #################### Agent Side Sync Data
    path('agent/<uuid:session_id>', views.CobrowseIOAgentPage),
    path('agent/sync/', views.SyncCobrowseIOAgent),
    path('agent/highlight/', views.SyncHighlightCobrowseIOAgent),
    path('agent/take-client-screenshot/', views.TakeClientScreenshot),
    path('archive/<uuid:session_id>', views.ArchiveCobrowsingLead),
    path('agent/change-active-status/', views.ChangeAgentActiveStatus),
    path('agent/close-session/', views.CloseCobrowsingSession),
    path('agent/share-session/', views.ShareCobrowsingSession),
    path('agent/get-meta-information/', views.GetCobrowsingMetaInformation),
    path('agent/save-details/', views.SaveAgentDetails),
    path('agent/add-new-agent/', views.AddNewAgentDetails),
    path('agent/save-cobrowsing-meta-details/', views.SaveCobrowsingMetaDetails),
    path('agent/search-lead/', views.SearchCobrowsingLead),
    path('agent/assign-lead/', views.AssignCobrowsingLead),
    path('agent/request-assist/', views.RequestCobrowsing),
    path('agent/mark-inactive/', views.MarkLeadInactive),
    path('agent/change-agent-activate-status/', views.ChaneAgentActivateStatus),
    # Analytics
    path('agent/basic-analytics/', views.GetAgentBasicAnalytics),
    path('agent/service-request-analytics/',
         views.GetAgentServiceRequestAnalytics),
    path('agent/agent-wise-request-analytics/', views.GetAgentWiseRequestAnalytics),
    path('agent/agent-wise-nps-analytics/', views.GetAgentNPSAnalytics),
]

# job_scheduler.start()
