from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

from EasyAssistSalesforceApp import views
from EasyAssistSalesforceApp import job_scheduler
from EasyAssistSalesforceApp import views_cognomeet as vd
from EasyAssistSalesforceApp import views_analytics_outbound


urlpatterns = [
    # Sales.AI Dashboard
    url(r'^$', views.SalesAILoginPage, name="easy-assist-home-page"),
    url(r'^sales-ai/dashboard/$', views.SalesAIDashboard, name="sales-dashboard"),
    url(r'^sales-ai/settings/$', views.SalesAnalyticsSettings,
        name="sales-settings-page"),
    url(r'^sales-ai/support-history/$',
        views.SalesSupportHistory, name="sales-support-history"),
    url(r'^sales-ai/sales-meetings/$',
        views.SalesMeetings, name="sales-meetings"),
    url(r'^sales-ai/meeting-audit-trail/$',
        vd.CognoVidAuditTrail, name="meeting-audit-trail/"),
    url(r'^sales-ai/unattended-leads/$',
        views.UnattendedLeadsDetails, name="unattended-leads/"),
    url(r'^sales-ai/export-support-history/$',
        views.ExportSalesSupportHistory, name="export-support-history"),
    url(r'^sales-ai/export-unattended-leads-details/$',
        views.ExportUnattentedLeadsDetals, name="export-unattended-leads-details"),
    url(r'^sales-ai/export-meeting-support-history/$',
        views.ExportMeetingSupportHistory, name="export-meeting-support-history"),
    url(r'^sales-ai/screen-recording-audit-trail/$', views.ScreenRecordingAuditTrail),
    url(r'^sales-ai/analytics/$',
        views.SalesAnalyticsDashboard, name="sales-analytics"),
    url(r'^sales-ai/cogno-meet-analytics/$',
        views.CognoMeetAnalyticsDashboard, name="sales-cogno-meet-analytics"),
    url(r'^sales-ai/analytics-outbound/$',
        views.SalesAnalyticsOutboundDashboard, name="sales-analytics-outbound"),
    url(r'^sales-ai/access-management/$',
        views.SalesAccessManagement, name="sales-access-management"),
    url(r'^sales-ai/customer-support-documents/',
        views.CustomerSupportDocuments, name="customer-support-documents"),
    url(r'^sales-ai/upload-customer-support-files/',
        views.UploadCustomerSupportDocuments, name="upload-customer-support-files"),
    url(r'^sales-ai/update-support-document-detail/$',
        views.UpdateSupportDocumentDetail, name="update-support-document-detail"),
    url(r'^sales-ai/upload-cobrowser-logo/$',
        views.UploadCobrowserLogo, name="upload-cobrowser-logo"),
    url(r'^sales-ai/delete-cobrowser-logo/$',
        views.DeleteCobrowserLogo, name="delete-cobrowser-logo"),
    url(r'^sales-ai/upload-connect-with-agent-icon/$',
        views.UploadConnectWithAgentIcon, name="upload-connect-with-agent-icon"),
    # url(r'^sales-ai/support-history/last-state/(?P<session_id>[a-zA-Z0-9-_]+)',
    #     views.RenderLastStateOfCobrowsingSession, name="last-state-page"),
    url(r'^sales-ai/audit-trail/$', views.SalesAuditTrail),
    url(r'^sales-ai/agent-audit-trail/$', views.SalesAgentAuditTrail),
    url(r'^sales-ai/livechat/$', views.SalesAILiveChatWindow),
    url(r'^sales-ai/cobrowse-video-conferencing-form/$', views.CobrowseForms),
    url(r'^sales-ai/cobrowse-video-conferencing-form/create/$',
        views.CreateCobrowseForms),
    url(
        r'^sales-ai/cobrowse-video-conferencing-form/edit/(?P<form_id>[0-9]+)$', views.EditCobrowseForms),
    url(r'^sales-ai/create-cobrowse-form/$', views.AddNewCobrowseForm),
    url(r'^sales-ai/save-cobrowse-form/$', views.SaveCobrowseForm),
    url(r'^sales-ai/change-cobrowse-form-agent/$', views.ChangeCobrowseFormAgent),
    url(r'^sales-ai/delete-video-conferencing-form/$',
        views.DeleteVideoConferencingForm),
    url(r'^sales-ai/delete-cobrowse-form-category/$',
        views.DeleteCobrowseFormCategory),
    url(r'^sales-ai/delete-cobrowse-form-category-question/$',
        views.DeleteCobrowseFormCategoryQuestion),
    
    # Client Side Sync Data
    url(r'^sales-ai.html$', views.SalesAIIframePage),
    url(r'^create-token/$', views.CobrowseIOCreateToken),
    url(r'^sync/$', views.SyncCobrowseIO),
    url(r'^highlight/$', views.HighlightCheckCobrowseIO),
    url(r'^initialize/$', views.CobrowseIOInitialize),
    url(r'^initialize-using-droplink/$', views.CobrowseIOInitializeUsingDroplink),
    url(r'^close-session/$', views.CobrowseIOCloseSession),
    url(r'^capture-client-screen/$', views.CobrowseIOCaptureClientScreen),
    url(r'^capture-lead/$', views.CobrowseIOCaptureLead),
    url(r'^submit-client-feedback/$', views.SubmitClientFeedback),
    url(r'^mark-lead-as-converted/$', views.MarkLeadAsConverted),
    url(r'^update-agent-assistant-request/$',
        views.UpdateAgentAssistantRequest),
    url(r'^update-agent-meeting-request/$',
        views.UpdateAgentMeetingRequest),
    url(r'^client-authentication/$', views.ClientAuthentication),
    url(r'^save-system-audit/$', views.SaveSystemAuditTrail),
    url(r'^sales-ai/client/livechat/$', views.SalesAIClientLiveChatWindow),
    url(r'^set-easyassist-customer/$', views.EasyAssistCustomerSet),
    # url(r'^customer/(?P<session_id>[a-zA-Z0-9-_]+)$',
    #     views.CobrowseIOClientPage),
    url(r'^available-agent-list/', views.AvailableAgentList),
    url(r'^download-file/(?P<file_key>[a-zA-Z0-9-_]+)/$', views.FileAccess),
    url(r'^get-cobrowsing-chat-history/$', views.GetClientCobrowsingChatHistory),
    # Agent Side Sync Data
    url(r'^agent/switch-agent-mode/$', views.SwitchAgentMode),
    url(r'^agent/change-active-status/$', views.ChangeAgentActiveStatus),
    url(r'^agent/save-cobrowsing-meta-details/$',
        views.SaveCobrowsingMetaDetails),
    url(r'^agent/(?P<session_id>[a-zA-Z0-9-_]+)$', views.CobrowseIOAgentPage),
    url(r'^agent/sync/$', views.SyncCobrowseIOAgent),
    url(r'^agent/highlight/$', views.SyncHighlightCobrowseIOAgent),
    url(r'^archive/(?P<session_id>[a-zA-Z0-9-_]+)$',
        views.ArchiveCobrowsingLead),
    url(r'^agent/close-session/$', views.CloseCobrowsingSession),
    url(r'^agent/share-session/$', views.ShareCobrowsingSession),
    url(r'^agent/get-meta-information/$', views.GetCobrowsingMetaInformation),
    url(r'^agent/save-details/$', views.SaveAgentDetails),
    url(r'^agent/save-cobrowse-agent-advanced-details/$', views.SaveCobrowseAgentAdvancedDetails),
    url(r'^agent/add-new-agent/$', views.AddNewAgentDetails),
    url(r'^agent/update-agent-details/$', views.UpdateAgentDetails),
    url(r'^agent/upload-user-details/$', views.UploadUserDetails),
    url(r'^agent/export-user-details/$', views.ExportUserDetails),
    url(r'^agent/download-user-details-excel-template/$', views.DownloadUserDetailsTemplate),
    url(r'^agent/resend-account-password/$', views.ResendAccountPassword),
    url(r'^agent/add-new-obfuscated-field/$', views.AddNewObfuscatedField),
    url(r'^agent/delete-obfuscated-fields/$', views.DeleteObfuscatedFields),
    url(r'^agent/add-new-search-tag-field/$', views.AddNewLeadHTMLField),
    url(r'^agent/delete-search-tag-fields/$', views.DeleteLeadHTMLFields),
    url(r'^agent/add-new-auto-fetch-field/$', views.AddNewAutoFetchField),
    url(r'^agent/delete-auto-fetch-fields/$', views.DeleteAutoFetchFields),
    url(r'^agent/save-agent-comments/$', views.SaveAgentComments),
    url(r'^agent/search-lead/$', views.SearchCobrowsingLead),
    url(r'^agent/assign-lead/$', views.AssignCobrowsingLead),
    url(r'^agent/assign-cobrowsing-session/$', views.AssignCobrowsingSession),
    url(r'^agent/request-assist/$', views.RequestCobrowsing),
    url(r'^agent/request-assist-meeting/$', views.RequestCobrowsingMeeting),
    url(r'^agent/check-meeting-status/$', views.CheckMeetingStatus),
    url(r'^agent/mark-inactive/$', views.MarkLeadInactive),
    url(r'^agent/get-lead-status/$', views.GetLeadStatus),
    url(r'^agent/change-agent-activate-status/$',
        views.ChangeAgentActivateStatus),
    url(r'^agent/save-cobrowsing-chat/$', views.SaveCobrowsingChat),
    url(r'^agent/get-cobrowsing-chat-history/$', views.GetCobrowsingChatHistory),
    url(r'^agent/get-support-agents/$', views.GetListOfSupportAgents),
    url(r'^agent/get-support-material/$', views.GetSupportMaterialAgent),
    url(r'^agent/export/(?P<meta_data_pk>\d+)/$', views.ExportCapturedData),
    url(r'^agent/save-document/$', views.SaveDocument),
    url(r'^agent/generate-drop-link/$', views.GenerateDropLink),
    url(r'^agent/set-notification-for-agent/$',
        views.SetNotificationForAgent),
    url(r'^pageshot/(?P<pageshot_id>\d+)$', views.EasyAssistPageShot),
    url(r'^agent/get-cobrowse-agent-comments/$',
        views.GetCobrowsingAgentComments),
    url(r'^agent/get-system-audit-trail-basic-activity/$',
        views.GetSystemAuditTrailBasicActivity),
    url(r'^agent/send-salesforce-notification/$', views.SendSalesforceNotification),
    # Inbound Analytics
    url(r'^agent/basic-analytics/$', views.GetAgentBasicAnalytics),
    url(r'^agent/service-request-analytics/$',
        views.GetAgentServiceRequestAnalytics),
    url(r'^agent/agent-wise-request-analytics/$',
        views.GetAgentWiseRequestAnalytics),
    url(r'^agent/agent-wise-nps-analytics/$', views.GetAgentNPSAnalytics),
    url(r'^agent/query-page-analytics/$', views.GetQueryPageAnalytics),
    url(r'^agent/get-visited-page-title-list/$', views.GetVisitedPageTitleList),
    url(r'^agent/export-not-initiated-customer-details/$', views.ExportNotInitiatedCustomerDetails),
    url(r'^agent/cogno-meet-basic-analytics/$', views.GetCognoMeetBasicAnalytics),
    url(r'^agent/cogno-meet-analytics/$', views.GetCognoMeetAnalytics),
    url(r'^agent/cogno-meet-daily-time-trend-analytics/$', views.GetCognoMeetDailyTimeTrendAnalytics),
    url(r'^agent/cogno-meet-agent-wise-analytics/$', views.GetAgentWiseCognoMeetAnalytics),
    url(r'^agent/cogno-meet-cobrowse-video-analytics/$', views.GetCognoMeetCobrowsingAnalytics),
    url(r'^agent/generate-video-meeting/$',
        vd.GenerateVideoConferencingMeet),
    # Outbound Analytics
    url(r'^agent/basic-analytics-outbound/$', views_analytics_outbound.GetAgentBasicAnalyticsOutbound),
    url(r'^agent/service-request-analytics-outbound/$',
        views_analytics_outbound.GetAgentServiceRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-request-analytics-outbound/$',
        views_analytics_outbound.GetAgentWiseRequestAnalyticsOutbound),
    url(r'^agent/agent-wise-nps-analytics-outbound/$', views_analytics_outbound.GetAgentNPSAnalyticsOutbound),
    url(r'^agent/query-page-analytics-outbound/$', views_analytics_outbound.GetQueryPageAnalyticsOutbound),
    url(r'^agent/get-visited-page-title-list-outbound/$', views_analytics_outbound.GetVisitedPageTitleListOutbound),

    ##################################################################
    ################################   CognoVid screen recording  ############
    url(r'^meeting/(?P<meeting_id>[a-zA-Z0-9-_]+)$', vd.CognoVidMeeting),
    url(r'^meeting-ended/(?P<meeting_id>[a-zA-Z0-9-_]+)$',
        vd.CognoVidMeetingEnded),
    # url(r'^scheduled-meetings/$', vd.CognoVidMeetingScheduled),
    url(r'^scheduled-meetings-list/$', vd.GetCognoVidScheduledMeetingsList),
    url(r'^authenticate-meeting-password/$', vd.CognoVidAuthenticatePassword),
    url(r'^save-meeting-duration/$', vd.CognoVidMeetingDuration),
    url(r'^save-meeting-notes/$', vd.CognoVidMeetingNotes),
    url(r'^save-meeting-chats/$', vd.CognoVidMeetingChats),
    # url(r'^get-client-agent-chats/$', vd.CognoVidGetClientAgentChat),
    url(r'^save-screen-recorded-data/', vd.SaveScreenRecordedData),
    url(r'^upload-cognovid-file-attachment/', vd.UploadCognoVidFileAttachment),
    url(r'^get-meet-support-agents/$', vd.GetListOfMeetSuportAgents),
    url(r'^get-meeting-forms/$', vd.GetListOfMeetingForms),
    # url(r'^get-meet-support-documents/$', vd.GetListOfMeetingSupportDocument),
    url(r'^request-agent-meeting/$', vd.RequestJoinMeeting),
    # url(r'^agent/save-video-meeting/$', vd.SaveVideoConferencingMeet),
    url(r'^agent/assign-video-meeting/$', vd.AssignVideoConferencingMeet),
    url(r'^invite-video-meeting-email/$', vd.InviteVideoMeetingEmail),
    url(r'^save-cobrowsing-screen-recorded-data/$',
        views.SaveCobrowsingScreenRecordedData),
    url(r'^check-agent-connected-or-not/$', vd.CheckAgentConnectedOrNot),
    url(r'^update-agent-join-status/$', vd.UpdateAgentJoinStatus),
    url(r'^save-client-recorded-data/', vd.SaveClientRecordedData),
    url(r'^save-client-location-details/', vd.SaveClientLocationDetails),
    url(r'^check-cobrowsing-meeting-status/', vd.CheckCobrowsingMeetingStatus),
    url(r'^save-meeting-screenshot/', vd.SaveCognoMeetScreenshot),
    # url(r'^pageshot/(?P<pageshot_id>\d+)$', views.EasyAssistPageShot),
    url(r'^client-meeting-feedback/', vd.ClientMeetingFeedback),
    url(r'^check-meeting-ended-or-not/', vd.CheckMeetingEndedOrNot),
    url(r'^cobrowse-data-collect/(?P<meeting_id>[a-zA-Z0-9-_]+)/(?P<form_id>[0-9]+)/$',
        vd.CobrowseVideoConferencingDataCollect),
    url(r'^cobrowse-data-collect/show/(?P<meeting_id>[a-zA-Z0-9-_]+)/(?P<form_id>[0-9]+)/$',
        vd.ShowCobrowseDataCollectForm),
    url(r'^save-cobrowse-collected-form-data/$',
        vd.SaveCobrowseCollectedFormData),

]

# Do not Use this scheduler in production
# job_scheduler.start()
